### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by whober0521** [whober0521/CSE6329#7]
- [ ] more complicated pw

- [x] redirect admin to home page after updating the user profile

- [x] reportedproblem.html should be a editable list.

- [x] add reportedproblem to repairer
